on: [push, pull_request]

name: Markdown Link Check

jobs:
  markdown-link-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
