on:
  push:
    branches:
      - master
  pull_request:

name: CI

jobs:
  build:
    name: Build ${{ matrix.build }}

    strategy:
      matrix:
        build:
          - macos
          # TODO: Needs clang and possibly other binaries
          # - android
        include:
          - build: macos
            runs-on: macos-latest
            use-cross: false
            # TODO: Too slow; see https://github.com/actions/runner-images/issues/1336
            build-in-pr: false
          # - build: android
          #   runs-on: ubuntu-22.04
          #   target: aarch64-linux-android
          #   use-cross: true


    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
        # Note: making the whole job conditional w.r.t matrix, instead of every step
        # is not supported and workarounds are very gnarly
        if: github.ref == 'refs/heads/master' || matrix.build-in-pr

      - uses: actions-rs/toolchain@v1
        if: github.ref == 'refs/heads/master' || matrix.build-in-pr
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          default: true
          profile: minimal

      - uses: Swatinem/rust-cache@v2
        if: github.ref == 'refs/heads/master' || matrix.build-in-pr

      - name: Build
        if: github.ref == 'refs/heads/master' || matrix.build-in-pr
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.extra-build-args }}
          use-cross: ${{ matrix.use-cross }}

      - name: Clippy
        if: github.ref == 'refs/heads/master' || matrix.build-in-pr
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: ${{ matrix.extra-build-args }} -- --deny warnings
          use-cross: ${{ matrix.use-cross }}
